### ISSUE TITLE
Dynamiczne sprawdzanie formularzy

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/sungate#1]

**Comment by dbetka** [comment]
Częściowo zrobione [tutaj](https://github.com/arbuz-team/sungate/commit/19087b1d08bb428226aa6bdcbfd51b96bf76bb19)! ; )

**Comment by arbuz93** [comment]
Aktualnie sprawdzamy tylko adres mailowy. Każdy klient ma przydzielony indywidualny klucz unique.

**Comment by dbetka** [comment]
Zrobione - ostatni commit w tym temacie [09c6fa9
](https://github.com/arbuz-team/sungate/commit/09c6fa9aa248e029416dd8ced3d8cfd52f05a3f1)
