### ISSUE TITLE
Wyświetlanie listy kategorii

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/sungate#10]
Zwracaj z bazy danych poprzez JSON listę wszystkich kategorii do pliku start.html

**Comment by arbuz93** [comment]
@Drego31 ??
Więcej szczegółów.

**Comment by dbetka** [comment]
Co jeszcze chciałbyś wiedzieć? @arbuz93

**Comment by arbuz93** [comment]
Wysyłam albo JSONa albo HTML. W jaki sposób mam to niby połączyć?
Mam to zrobić, gdy pytasz POSTem? Pod jaką zmienną?
@Drego31

**Comment by dbetka** [comment]
Hym no tak... to nie JSONem tylko daj mi listę w django bym mógł ją w pętli wyświetlić @arbuz93
