### ISSUE TITLE
Lista życzeń klienta [produkty]

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/sungate#18]
### Stworzenie możliwości zapisania produktu na swojej liście lubianych bądź "liście przyszłych zakupów", by móc po jakimś czasie do niego wrócić/ łatwo go znaleźć.

**Comment by arbuz93** [comment]
https://github.com/arbuz-team/sungate/commit/6fba9cccced461034bdb138e582075ffd2a49a3b
