### ISSUE TITLE
Wyświetlanie szablonów listy produktów

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/sungate#2]
### Wyświetlanie szablonów listy produktów, w tym:
- Lista
- Kafelki

**Comment by dbetka** [comment]
Myślę, że produkty mogą zawierać zdjęcie, cenę i opis @arbuz93

**Comment by dbetka** [comment]
No i nazwę! @arbuz93

**Comment by arbuz93** [comment]
Zapomniałem dodać informacji, których commitów się tyczy:
https://github.com/arbuz-team/sungate/commit/71c58727c8ac47833173d3e95db36321cd528c52
https://github.com/arbuz-team/sungate/commit/d4a8192b029642b7b87e832fb8c27bbb0f9b4c52

**Comment by arbuz93** [comment]
Poprzednie commity są nieważne / przestarzałe.
https://github.com/arbuz-team/sungate/commit/784579b4ad8bdeb86c8683d33a1fa17e3c54abdf

**Comment by arbuz93** [comment]
https://github.com/arbuz-team/sungate/commit/402b3ce4fa3a2fb13026350870799e1cbbcb29d1

**Comment by arbuz93** [comment]
`Lista` does not exist
