### ISSUE TITLE
Nawigator

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/sungate#21]
Zrobiłem nawigację, gdzie aktualnie znajduje się klient na stronie. Umieściłem ją w index.html i twoim zadaniem jest ustawienie tego tak, żeby na każdej stronie się odświeżał nawigator.
Więcej informacji znajdziesz w ostatnim tutaj:
https://github.com/arbuz-team/sungate/commit/5df9e4858383004add4eed2cccbb73fc0a663700

- [x] All tasks @arbuz93
- [x] All tasks @Drego31

**Comment by arbuz93** [comment]
https://github.com/arbuz-team/sungate/commit/8f1b5001fdb4e8934e0bbafe5e38748717290f24

**Comment by dbetka** [comment]
https://github.com/arbuz-team/sungate/commit/962b5f7132b3b6c307779d7af99d39436217b517
