### ISSUE TITLE
Get country code

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/sungate#22]
- [x] Sam wiesz co masz zrobić xD
- [ ] Ja zrobię interfejs do zmiany języka

**Comment by Drego31** [comment]
@arbuz93 Wykonaj podpunkt pierwszy - przygotuj dla mnie adres, z którego będę dostawał IP aktualnego odwiedzającego.

**Comment by arbuz93** [comment]
Zrobiłem wszystko sam. Mogłem to zrobić w django. @Drego31 
https://github.com/arbuz-team/sungate/commit/48c3ba70b683d0369dbfd09e99c9242e85dbe0a3
https://github.com/arbuz-team/sungate/commit/6ce8e0473e6a8e3e9b3ee6657a7e23f18b9c089b
Nie zrobiłem komunikatu o zmianie języka, ale pobieranie IP i automatyczne przekierowanie na język kraju zrobione.

**Comment by dbetka** [comment]
https://github.com/arbuz-team/sungate/commit/0e6a792920c5fdb7f3501e8860ae7d23d1d1aa1b

Trzeba jeszcze dodać odpowiednie adresy na sam koniec. @arbuz93

**Comment by arbuz93** [comment]
Interface to change language should be in content. @Drego31

**Comment by arbuz93** [comment]
https://github.com/arbuz-team/sungate/commit/38c3fda6f3937d1d21afcfc110676ad01cfb789e
https://github.com/arbuz-team/sungate/commit/a56651e1a850b379d5ae5180b636720677f10fe7
