### ISSUE TITLE
Authorization and edition profile

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/sungate#28]
Tasks:
- [ ] Secure fields in mini form #27 
- [x] Create the ability to change password 
- when forget
- when want change password

**Comment by arbuz93** [comment]
https://github.com/arbuz-team/sungate/commit/290bd99b8e43a712fa76b39f76c5af7507e6f9bc
https://github.com/arbuz-team/sungate/commit/8c26d92505c5e94207a5a2e72ae9a569a66ba3d1
