### ISSUE TITLE
Nie działa wylogowywanie

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/sungate#4]
Przy wylogowywaniu następuje zapętlone przekierowanie.

![screenshot_20161020_183731](https://cloud.githubusercontent.com/assets/6503362/19569015/47608cda-96f4-11e6-8a74-feb02c29565f.png)

**Comment by arbuz93** [comment]
Fajnie. To jest redirect. Możliwe, że problem jest właśnie przy dynamicznej obsłudze przekierowań. Przeanalizuję temat dokładnie, gdy znajdę chwilę czasu. @Drego31

**Comment by dbetka** [comment]
Okej @arbuz93

**Comment by arbuz93** [comment]
Problem rozwiązany przy ostatnich zmianach obsługi wydarzeń dynamicznych.
Zamykam.
