### ISSUE TITLE
Komunikat 404 - przekierowanie

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/sungate#5]
@arbuz93 Mam propozycję. Jeśli adres będzie błędny to niech przenosi normalnie na index.html
Mam już napisaną do tego obsługę więc nie będzie z tym problemu (poprostu wczyta jako treść komunikat 404)

**Comment by arbuz93** [comment]
Aktualnie pracujemy na wersji Debug, co pomaga zrozumieć błędy, które pojawiają się podczas błędnych przekierowań. Gdy tylko przejdziemy na wersję Release, ustawię taką obsługę błędów, tak jak na naszej poprzedniej stronie internetowej htttp://www.asbhp.pl/
@Drego31
