### ISSUE TITLE
Stworzenie interfejsu płatności

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/sungate#8]
Stworzenie interfejsu do obsługi płatności przelewem i przy odbiorze

**Comment by arbuz93** [comment]
https://pl.python.org/forum/index.php?topic=3718.0;wap2
https://django-paypal.readthedocs.io/en/stable/

**Comment by arbuz93** [comment]
PayPal: https://github.com/arbuz-team/sungate/commit/0b56d890e66cdc6ee23a714b8db34f1d01705355

**Comment by arbuz93** [comment]
http://developers.payu.com/pl/quick_start.html

**Comment by arbuz93** [comment]
Dotpay: https://github.com/arbuz-team/sungate/commit/7410ba234df9242f531ca6b5257f359da4caab65
